# These are supported funding model platforms

github: ["ViniciusRed"]
patreon: #
open_collective: #
ko_fi: #
tidelift: #
community_bridge: #
liberapay: #
issuehunt: #
otechie: #
lfx_crowdfunding: #
custom: ["https://app.picpay.com/user/vinicius.almeida1"]
